repos:

  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
        exclude: ^postprocessing_h5py/|^postprocessing_fenics/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        exclude: ^postprocessing_h5py/|^postprocessing_fenics/